name: permissionless-batches

services:
  relayer-batch-production:
    build:
      context: ../
      dockerfile: build/dockerfiles/recovery_permissionless_batches.Dockerfile
    container_name: permissionless-batches-relayer
    volumes:
      - ./conf/relayer/config.json:/app/conf/config.json
      - ./conf/genesis.json:/app/conf/genesis.json
    command: "--config /app/conf/config.json"
    profiles:
      - batch-production-submission
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17.0
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_DB: scroll
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 1s
      retries: 10
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  coordinator:
    build:
      context: ../
      dockerfile: build/dockerfiles/coordinator-api.Dockerfile
    volumes:
      - ./conf/coordinator/config.json:/app/conf/config.json
      - ./conf/genesis.json:/app/conf/genesis.json
    command: "--config /app/conf/config.json --http.port 8390 --verbosity 5"
    profiles:
      - proving
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8390/coordinator/v1/challenge"]
      interval: 1s
      timeout: 1s
      retries: 10
      start_period: 5m

  coordinator-cron:
    build:
      context: ../
      dockerfile: build/dockerfiles/coordinator-cron.Dockerfile
    volumes:
      - ./conf/coordinator/:/app/conf
    command: "--config /app/conf/config.json --verbosity 3"
    profiles:
      - proving
    depends_on:
      db:
        condition: service_healthy


  proving-service-chunk:
    image: scrolltech/sdk-cloud-prover:sindri-v0.0.5
    platform: linux/amd64
    command: "--config /app/config.json"
    profiles:
      - proving
    environment:
          PROVER_NAME_PREFIX: "sindri_chunk"
          CIRCUIT_TYPE: 1 # 1 for chunk proving
          N_WORKERS: 1
    volumes:
      - ./conf/proving-service/chunk/:/app/
      - ./conf/proving-service/config.json:/app/config.json
    depends_on:
      coordinator:
        condition: service_healthy

  proving-service-batch:
    image: scrolltech/sdk-cloud-prover:sindri-v0.0.5
    platform: linux/amd64
    command: "--config /app/config.json"
    profiles:
      - proving
    environment:
      PROVER_NAME_PREFIX: "sindri_batch"
      CIRCUIT_TYPE: 2 # 2 for batch proving
      N_WORKERS: 1
    volumes:
      - ./conf/proving-service/batch/:/app
      - ./conf/proving-service/config.json:/app/config.json
    depends_on:
      coordinator:
        condition: service_healthy

  proving-service-bundle:
    image: scrolltech/sdk-cloud-prover:sindri-v0.0.5
    platform: linux/amd64
    command: "--config /app/config.json"
    profiles:
      - proving
    environment:
      PROVER_NAME_PREFIX: "sindri_bundle"
      CIRCUIT_TYPE: 3 # 3 for bundle proving
      N_WORKERS: 1
    volumes:
      - ./conf/proving-service/bundle/:/app
      - ./conf/proving-service/config.json:/app/config.json
    depends_on:
      coordinator:
        condition: service_healthy

volumes:
    db_data: